version: '3.8'

services:
  tatar-by-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: tatar-by-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - tatar-by-network

networks:
  tatar-by-network:
    driver: bridge
